### ISSUE TITLE
Rushy fails to run on my test jenkins setup

### ISSUE THREAD

**Issue by oleggromov** [luchkonikita/rushy#1]
We have a job that runs Rushy inside of a Docker container from Jenkins. If I run rushy like this:
```
rushy --config=./front/configs/rushy.json
```

Where the config is as simple as that:

```
{
    "urls": [
      "https://www.mywebsite.com/"
    ],
    "storeDir": "./front/reports",
    "skipAudits": []
  }
```
`mywebsite.com` works, I just replaced the real name with a placeholder. 

I'm getting the following error in the job log:

```
04:32:10 $ rushy --config=./front/configs/rushy.json
04:32:37 (node:433) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:33394
04:32:37     at Object._errnoException (util.js:992:11)
04:32:37     at _exceptionWithHostPort (util.js:1014:20)
04:32:37     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
04:32:37 (node:433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
04:32:37 (node:433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

At the same time, plain `lighthouse` called from the very same job works. I run it like this:
```
yarn lighthouse --output=html --output=json --output-path=/tmp/mywebsite.com --chrome-flags=\"--headless --no-sandbox\" --no-enable-error-reporting https://mywebsite.com
```

**Comment by luchkonikita** [comment]
Should be fixed by https://github.com/luchkonikita/rushy/commit/053a28e45bc5d1a36fe552f1b6f669408c595be8
